apiVersion: v1
kind: Service
metadata:
  name: loandoc
  namespace: portfolio
spec:
  type: NodePort
  selector: { app: loandoc }
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30800
